### ISSUE TITLE
Autowired issues on Spring 4 (4.1.4) and when java SecurityManager is set

### ISSUE THREAD

**Issue by andri-kruus** [spring-projects/spring-framework-issues#90]
Spring fails to Autowire

....
Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
        at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
        at org.springframework.cglib.proxy.Enhancer.create(Enhancer.java:285)
        at org.springframework.aop.framework.CglibAopProxy.createProxyClassAndInstance(CglibAopProxy.java:227)
        at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.ja
va:66)
        at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:202)
        ... 48 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
        ... 53 more

Caused by: java.lang.LinkageError: loader (instance of org/apache/catalina/loader/WebappClassLoader): attempted duplica
te class definition for name: "com/*******/******/services/ProcessorService$$EnhancerBySpringCGLIB$$d39a5e8b"
at java.lang.ClassLoader.defineClass1(Native Method)

and there is no way to resolve such unless giving AllPermissions that you probaly dont want to do..
no matter what you do
when downgarding to spring 3 latest all well

**Comment by snicoll** [comment]
This is not the issue tracker of the spring framework. Please create an issue at https://jira.spring.io/browse/SRP - When you do, please provide more details (a sample project would help). Thanks!
